
version: '3'

services:
  redis1:
    image: redis
    ports:
      - "6379:6379"

  redis2:
    image: redis
    ports:
      - "6380:6379"
    command: redis-server --port 6379 --slaveof redis1 6379

  redis3:
    image: redis
    ports:
      - "6381:6379"
    command: redis-server --port 6379 --slaveof redis1 6379
    
  sentinel1:
    image: redis
    ports:
      - "26379:26379"
    command: >
      redis-sentinel /usr/local/etc/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/sentinel.conf

  sentinel2:
    image: redis
    ports:
      - "26380:26379"
    command: >
      redis-sentinel /usr/local/etc/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/sentinel.conf

  sentinel3:
    image: redis
    ports:
      - "26381:26379"
    command: >
      redis-sentinel /usr/local/etc/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/sentinel.conf